version: "3.7"

services:
    db:
        image: postgres
        container_name: test-graphql-db-${TIER}
        restart: always
        env_file: .env.${TIER}
        ports:
            - 5432:5432
        volumes:
            - ./data-pg-${TIER}:/var/lib/postgresql/data
        networks:
            - apinet

networks:
    apinet:
        driver: bridge
