version: "3.7"

services:
    db:
        image: postgres
        container_name: test-graphql-db
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - ./data-pg:/var/lib/postgresql/data
        networks:
            - apinet

networks:
    apinet:
        driver: bridge
